minimumReleaseAgeExclude:
  - '@deepseek-ai/cosmokit@1.8.4'
  - '@deepseek-ai/schemastery@3.18.3'
  - '@deepseek-ai/cordis@4.0.3'
  - '@deepseek-ai/dsh-brand@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-client-locale@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-client-store@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-client-ui-primitives@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-home-paths@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-ptc-runtime@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-sandbox-policy@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-sandbox@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-tools@0.1.7-alpha.1'
  - '@deepseek-ai/dsh-util-values@0.1.7-alpha.1'
