import { spawn } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { dshHomePath } from '@deepseek-ai/dsh-home-paths'

export const inject = ['timer']

// 隐藏启动器：wscript.exe（GUI 子系统，无控制台窗口）执行同名目录下的
// launcher vbs，由 vbs 以隐藏窗口、独立进程方式运行重启脚本。
const launcherVbs = fileURLToPath(new URL('dsh-web-restart-launcher.vbs', import.meta.url))

const IS_WINDOWS = process.platform === 'win32'
// macOS 与 Linux 走同一条 POSIX 链路（/bin/sh）。其它平台（aix 等）不启用。
const IS_POSIX = process.platform === 'darwin' || process.platform === 'linux'

/**
 * 生成 POSIX 自动重启脚本（纯函数：契约门可直接断言，不需要真的杀进程）。
 *
 * 语义与 Windows 的 .cmd 一致：先 SIGTERM 旧进程，等它退出（最多 10 秒，超时 SIGKILL），
 * 再以**原命令**（`process.execPath` + `process.argv.slice(1)`）在新的独立进程里重启，
 * 输出追加到 `<DSH_HOME>/autostart/dsh-web-restart.log`。
 * 所有参数都做 POSIX 单引号转义（`'` → `'\''`），路径含空格/引号也不会破。
 * @param {{pid: number, cwd: string, execPath: string, args: string[], logPath: string}} spec
 * @returns {string} 可交给 `/bin/sh` 执行的脚本文本
 */
export function buildPosixRelaunchScript(spec) {
  const quote = (value) => "'" + String(value).replace(/'/g, "'\\''") + "'"
  const command = [spec.execPath, ...spec.args].map(quote).join(' ')
  return [
    '#!/bin/sh',
    '# generated by dsh-session-toolkit (web restart); safe to delete',
    'sleep 0.5',
    'kill -TERM ' + spec.pid + ' 2>/dev/null',
    'i=0',
    'while kill -0 ' + spec.pid + ' 2>/dev/null; do',
    '  i=$((i+1))',
    '  if [ "$i" -ge 100 ]; then kill -KILL ' + spec.pid + ' 2>/dev/null; break; fi',
    '  sleep 0.1',
    'done',
    'cd ' + quote(spec.cwd) + ' || exit 1',
    'exec ' + command + ' >> ' + quote(spec.logPath) + ' 2>&1',
    '',
  ].join('\n')
}

export function apply(ctx, cfg) {
  // Config 分键（webRestart.scriptPath 可选覆盖 / spawnDelayMs），缺省兜底默认值。
  // scriptPath 缺省时由 DSH home 推导（$DSH_HOME → ~/.dsh，见 @deepseek-ai/dsh-home-paths）：
  // Windows 是 .cmd，macOS/Linux 是 .sh。
  const configuredScriptPath = (cfg && typeof cfg.scriptPath === 'string' && cfg.scriptPath.length > 0)
    ? cfg.scriptPath
    : ''
  const scriptPath = configuredScriptPath
    || dshHomePath('autostart', IS_WINDOWS ? 'dsh-web-restart.cmd' : 'dsh-web-restart.sh')
  const spawnDelayMs = (cfg && typeof cfg.spawnDelayMs === 'number') ? cfg.spawnDelayMs : 500
  const restartLogPath = dshHomePath('autostart', 'dsh-web-restart.log')
  // 平台能力：Windows 走 wscript+.cmd；macOS/Linux 走 /bin/sh——**配置了 scriptPath 就用它**，
  // 否则按当前进程的命令行自动重启（无需用户准备任何脚本）。其余平台明确不可用。
  const available = IS_WINDOWS || IS_POSIX
  const mode = IS_WINDOWS ? 'windows-script' : (configuredScriptPath.length > 0 ? 'posix-script' : 'posix-relaunch')
  let inFlight = false

  // 一次性挂 error/exit 监听并 unref：脚本结束（成功或失败）即重置 inFlight。
  // 非零退出码单独告警——找不到脚本/脚本内部失败时只触发 'exit'（无 'error' 事件）。
  function launchDetached(command, args) {
    let child
    try {
      child = spawn(command, args, { detached: true, windowsHide: true, stdio: 'ignore', shell: false })
    } catch (e) {
      console.warn('[dsh-web-restart] spawn failed: ' + (e && e.message ? e.message : String(e)))
      inFlight = false
      return
    }
    child.on('error', (e) => {
      console.warn('[dsh-web-restart] spawn error: ' + (e && e.message ? e.message : String(e)))
      inFlight = false
    })
    child.on('exit', (code) => {
      if (code !== 0) console.warn('[dsh-web-restart] restart script exited with code ' + code)
      inFlight = false
    })
    child.unref()
  }

  // 返回 null 表示可以继续；返回字符串表示拒绝原因（POST 直接 500，client 立即报错而不是空转）。
  function precheck() {
    if (configuredScriptPath.length === 0 && mode === 'posix-relaunch') {
      if (process.argv.length < 2) return 'cannot self-relaunch: process.argv is too short; set webRestart.scriptPath instead'
      return null
    }
    if (!fs.existsSync(scriptPath)) return 'restart script not found: ' + scriptPath
    return null
  }

  function launch() {
    if (IS_WINDOWS) {
      // 用 wscript + launcher vbs 启动重启脚本：wscript.exe 无控制台窗口，
      // vbs 以 sh.Run(..., 0, False) 隐藏窗口 + 异步独立运行，从而——
      //  1) 不弹出 cmd 控制台窗口（detached cmd 会创建新 console，windowsHide 对 detached 不可靠）；
      //  2) 重启脚本作为独立进程，父进程（GUI，被脚本 taskkill）退出后仍完整执行。
      // 注意：不要手动给 wscript 的参数加引号；spawn(shell:false) 会按 Windows 规则自动转义。
      launchDetached('wscript.exe', [launcherVbs, scriptPath])
      return
    }
    if (mode === 'posix-script') {
      launchDetached('/bin/sh', [scriptPath])
      return
    }
    // POSIX 自动重启：把「杀旧 → 等退出 → 按原命令重启」写成一次性脚本，再以独立进程执行。
    // 脚本落在 os.tmpdir()（可读可查，名字带 pid），无需用户准备任何文件。
    try {
      fs.mkdirSync(path.dirname(restartLogPath), { recursive: true, mode: 0o700 })
    } catch (e) {
      console.warn('[dsh-web-restart] cannot create log directory: ' + (e && e.message ? e.message : String(e)))
    }
    const generated = path.join(os.tmpdir(), 'dsh-web-restart-' + process.pid + '.sh')
    const body = buildPosixRelaunchScript({
      pid: process.pid,
      cwd: process.cwd(),
      execPath: process.execPath,
      args: process.argv.slice(1),
      logPath: restartLogPath,
    })
    try {
      fs.writeFileSync(generated, body, { mode: 0o700 })
    } catch (e) {
      console.warn('[dsh-web-restart] cannot write relaunch script: ' + (e && e.message ? e.message : String(e)))
      inFlight = false
      return
    }
    launchDetached('/bin/sh', [generated])
  }

  // webServer 为可选服务：用 ctx.inject 等它就绪（apply 时刻一次性 ctx.get 会让
  // 「webServer 晚于本插件就绪」变成路由永久 404，且没有任何日志）。
  ctx.inject(['webServer'], (childCtx) => {
    const webServer = childCtx.get('webServer')
    if (!webServer) return
    // P1-1：register 返回 disposer，包 ctx.effect 绑定生命周期（热重载不重复注册、卸载时注销）。
    childCtx.effect(() => webServer.register({
      kind: 'exact',
      path: '/api/restart',
      handler: (req, res) => {
        if (req.method === 'GET') {
          // 健康探测端点：恒 200（新服务器加载本插件后路由自动恢复，客户端轮询依赖它）；
          // available 供 client 判断本机是否支持重启；mode 供诊断（windows-script /
          // posix-script / posix-relaunch）。
          res.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' })
          res.end(JSON.stringify({ ok: true, available, mode, platform: process.platform }))
          return
        }
        if (req.method === 'POST') {
          if (!available) {
            res.writeHead(501, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: 'restart is not supported on ' + process.platform }))
            return
          }
          if (inFlight) {
            res.writeHead(409, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: 'restart already in flight' }))
            return
          }
          const refusal = precheck()
          if (refusal !== null) {
            res.writeHead(500, { 'content-type': 'application/json' })
            res.end(JSON.stringify({ ok: false, error: refusal }))
            return
          }
          inFlight = true
          res.writeHead(202, { 'content-type': 'application/json' })
          res.end(JSON.stringify({ ok: true }))
          // 缓冲 500ms 让 202 送达浏览器后再 spawn（服务器随后自毁）；
          // 用 ctx.timeout（timer 服务）：插件卸载时回调被清理，不会在卸载后触发 spawn。
          ctx.timeout(launch, spawnDelayMs)
          return
        }
        res.writeHead(405, { 'content-type': 'application/json' })
        res.end(JSON.stringify({ ok: false, error: 'method not allowed' }))
      },
    }), 'dsh-web-restart: routes')
  })
}
